name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+**"

env:
  QT_SRC_DIR: ~/Qt/git/src
  QT_STATIC_DIR: ~/Qt/git/output

permissions:
  contents: write

jobs:
  mac:
    name: build and publish
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - name: set environment variables
        run: |
          echo "ASSET=CanvasSync-${{ matrix.os }}.tar.gz">>$GITHUB_ENV

      - uses: actions/checkout@v3
      - run: |
          curl -fLo qt_static.tar.gz https://github.com/nguyenvukhang/qt-static/releases/latest/download/qt-6.4.2.${{ matrix.os }}.tar.gz
          mkdir -p ${{ env.QT_STATIC_DIR }}
          tar -xvzf qt_static.tar.gz && mv qt_output/* ${{ env.QT_STATIC_DIR }}
          xattr -cr ${{ env.QT_STATIC_DIR }}

      - run: |
          ls ${{ env.QT_STATIC_DIR }}

      # build canvas-sync
      - run: make build
        env:
          QT_STATIC_DIR: ${{ env.QT_STATIC_DIR }}

      - run: |
          cd build
          tar -zcvf ${{ env.ASSET }} CanvasSync.app
          mv ${{ env.ASSET }} ..

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.ASSET }}
          generate_release_notes: true
