name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+**"

permissions:
  contents: write

jobs:
  helloworld:
    name: hello
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Release.txt
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
