name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+**"

permissions:
  contents: write

jobs:
  mac:
    name: Mac
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: brew install ninja
      - uses: actions/cache/restore@v3
        with:
          key: ${{ runner.os }}-qt-static
          path: ${{ env.QT_OUTPUT_DIR }} ${{ env.QT_SRC_DIR }}

      # build static Qt libraries
      - run: make get-qt
      - run: make build-qt
        id: qt_static_build

      # build canvas-sync
      - run: make build
      - run: |
          cd build
          tar -zcvf CanvasSync.tar.gz CanvasSync.app
          mv CanvasSync.tar.gz ..

      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            CanvasSync.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
